version: 1.0.{build}
image: Visual Studio 2017
        

build_script:
- ps: >-
   
    (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install.ps1") | iex 

- cmd: >-    
    
    cd build

    refreshenv

    dotnet script build.csx pack

test: off
artifacts:
- path: /**/LightInject.Nancy*.nupkg
  name: NuGet Packages
deploy:
  provider: NuGet  
  api_key:
    secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm
  skip_symbols: false  
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true